language: node_js
node_js:
- "8.3"
os:
- osx
osx_image: xcode61
rvm:
- 2.2
cache:
  directories:
    - ./Unity
before_install:
- chmod a+x ./Travis/installUnity.sh
- npm install -g npm@6.x
install:
- ./Travis/installUnity.sh
- npm install @semantic-release/exec
before_script:
- chmod a+x ./Travis/createProject.sh
- chmod a+x ./Travis/installSDK.sh
- chmod a+x ./Travis/runTests.sh
- chmod a+x ./Travis/build.sh
script:
- ./Travis/createProject.sh
- ./Travis/installSDK.sh
# - ./Travis/runTests.sh
# - ./Travis/build.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
